# Multilayer perceptron(MLP)

## One-hot encoding for multi class classification

### Integer encoding
- 수학과 &rightarrow; 0
- 생명과학과 &rightarrow; 1
- 물리학과 &rightarrow; 2
- 화학과 &rightarrow; 3

### One-Hot encoding
- 0 &rightarrow; [1,0,0,0]
- 1 &rightarrow; [0,1,0,0]
- 2 &rightarrow; [0,0,1,0]
- 3 &rightarrow; [0,0,0,1]

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()
x = tf.constant([0, 1, 2, 3])
one_hot = tf.one_hot(x, depth=4)
print(one_hot.eval())
sess.close()

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Output of MLP

![mlp](./mlp.png)

<div align="right">
http://cs231n.github.io/neural-networks-1/
    </div>

### possible activation?

$$\mathbf{x}'[i] = \begin{cases}
1\quad \text{if} \; \max(\mathbf{x})=\mathbf{x}[i]\\
0 \quad \text{otherwise}
\end{cases}$$

### possible activation?
$$\mathbf{x}'[i] = \frac{\mathbf{x}[i]-\min(\mathbf{x})}{\max(\mathbf{x})-\min(\mathbf{x})}$$

### Softmax activation
$$ f(\mathbf{x})[i] = \frac{\mathrm{e}^{\mathbf{x}[i]}}{\sum_{k=1}^{K}\mathrm{e}^{\mathbf{x}[i]}}$$

In [3]:
sess = tf.InteractiveSession()
x = tf.constant([4, -1.3, 1.1, 2], np.float32)
softmax = tf.nn.softmax(x, axis=-1)
print(softmax.eval())
print(tf.reduce_sum(softmax).eval())
sess.close()

[0.836575   0.00417584 0.04603105 0.11321811]
1.0


## Loss of MLP

$$\text{Cross-entropy}= -\sum^N_{i=1}p_i \log q_i$$  


In [5]:
sess = tf.InteractiveSession()
labels = tf.constant([0, 1, 0, 0], np.float32)

weight_sum = tf.constant([4, -1.3, 1.1, 2], np.float32)
softmax = tf.nn.softmax(weight_sum)
loss = -tf.reduce_sum(labels * tf.log(softmax))
print(loss.eval())
sess.close()

5.4784393
